pipeline {
    agent any
    tools {
    maven 'myMaven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            when {
                branch 'master'
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            when {
                branch 'production'
            }
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
